// frontend/src/config.js
// Default configuration — mirrors backend PricingScenarioInput defaults
// (backend/models.py). Keep the two in sync.

export const defaultConfig = {
  assumptions: {
    tool_access_period_months: 5,
    contingency_rate: 0.15,
    mentor_hours_per_week: 4.0,
    mentor_delivery_weeks: 15,
    mentor_hourly_rate_eur: 20.0,
    internal_team_active_months: 5,
    usd_to_eur_rate: 0.86,
    vat_rate: 0.19,
    vat_treatment: 'small_business',
    payment_processing_fee_rate: 0.023,
    displayed_price_includes_vat: true,
    target_cash_surplus_margin: 0.05,
    down_payment_rate: 0.30,
  },
  workstreams: {
    itsa: 10,
    data: 10,
    marketing: 10,
    product: 10,
  },
  tools: {
    itsa: {
      jira_cloud: 0,
      jira_work_mgmt: 8,
      google_workspace: 6,
      google_cloud: 0,
      password_mgr: 5,
      slack: 0,
      dbt_core: 0,
      postgresql: 0,
      motherduck: 0,
      superset: 0,
      github_actions: 0,
      webflow: 0,
      ghost: 0,
      figma: 0,
      beehiiv: 0,
      canva: 0,
      google_analytics: 0,
    },
    data: {
      jira_cloud: 0,
      jira_work_mgmt: 8,
      google_workspace: 6,
      google_cloud: 8,
      password_mgr: 5,
      slack: 0,
      dbt_core: 0,
      postgresql: 0,
      motherduck: 0,
      superset: 0,
      github_actions: 0,
      webflow: 0,
      ghost: 0,
      figma: 0,
      beehiiv: 0,
      canva: 0,
      google_analytics: 0,
    },
    marketing: {
      jira_cloud: 0,
      jira_work_mgmt: 8,
      google_workspace: 6,
      google_cloud: 0,
      password_mgr: 5,
      slack: 0,
      dbt_core: 0,
      postgresql: 0,
      motherduck: 0,
      superset: 0,
      github_actions: 0,
      webflow: 18,
      ghost: 9,
      figma: 0,
      beehiiv: 0,
      canva: 0,
      google_analytics: 0,
    },
    product: {
      jira_cloud: 0,
      jira_work_mgmt: 8,
      google_workspace: 6,
      google_cloud: 0,
      password_mgr: 5,
      slack: 0,
      dbt_core: 0,
      postgresql: 0,
      motherduck: 0,
      superset: 0,
      github_actions: 0,
      webflow: 0,
      ghost: 0,
      figma: 0,
      beehiiv: 0,
      canva: 0,
      google_analytics: 0,
    },
  },
  internal_team: {
    active_months: 5,
    founder_solomon: { monthly: 500 },
    founder_david: { monthly: 500 },
    founder_akua: { monthly: 500 },
    volunteers: { count: 2, monthly_each: 218.72 },
    intern: { count: 1, monthly: 218.60 },
  },
  operational: {
    notion: { cost_basis: 'per_user_month', unit_cost: 13.68, quantity: 4, active_months: 5 },
    render: { cost_basis: 'fixed_month', unit_cost: 15.38, quantity: 1, active_months: 5 },
    resend: { cost_basis: 'fixed_month', unit_cost: 0, quantity: 1, active_months: 5 },
    calendly: { cost_basis: 'fixed_month', unit_cost: 0, quantity: 1, active_months: 5 },
    aws: { cost_basis: 'fixed_month', unit_cost: 0, quantity: 1, active_months: 5 },
    bitwarden: { cost_basis: 'per_user_month', unit_cost: 3.42, quantity: 6, active_months: 5 },
    namecheap: { cost_basis: 'fixed_annual', unit_cost: 100, quantity: 1, active_months: 5 },
  },
  other_costs: {
    legal_review: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    tax_adviser: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    bookkeeping: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    payment_processing: { amount: 0, is_percentage_of_revenue: true, percentage_rate: 0.023 },
    insurance: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    recruitment_marketing: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    refund_reserve: { amount: 0, is_percentage_of_revenue: true, percentage_rate: 0 },
    gdpr_review: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    certificates: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    travel_venue: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    bank_charges: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
    accreditation: { amount: 0, is_percentage_of_revenue: false, percentage_rate: null },
  },
  pricing: {
    early: { seats: 6, price: 649 },
    standard: { seats: 10, price: 699 },
    installment: { seats: 4, price: 720 },
  },
  launch_gates: {
    confirmed_participants: 0,
    minimum_confirmed_participants: 16,
    secured_revenue_to_date: 0,
    minimum_secured_revenue: 10000,
  },
  cash_flow_timing: {
    revenue_collection_profile: [0.40, 0.25, 0.20, 0.10, 0.05],
    cost_payment_profile: [0.25, 0.25, 0.20, 0.20, 0.10],
    phase_labels: ['Pre-launch', 'Month 1', 'Month 2', 'Month 3', 'Extension'],
  },
}

export const workstreamLabels = {
  itsa: 'IT Systems Admin',
  data: 'Data Analytics / Engineering',
  marketing: 'Digital Marketing',
  product: 'Product / Project Management',
}

export const toolLabels = {
  jira_cloud: 'Jira Cloud',
  jira_work_mgmt: 'Jira Work Management',
  google_workspace: 'Google Workspace / M365',
  google_cloud: 'Google Cloud',
  password_mgr: '1Password / Bitwarden',
  slack: 'Slack',
  dbt_core: 'dbt Core CLI',
  postgresql: 'PostgreSQL',
  motherduck: 'MotherDuckDB',
  superset: 'Apache Superset',
  github_actions: 'GitHub Actions',
  webflow: 'Webflow',
  ghost: 'Ghost',
  figma: 'Figma',
  beehiiv: 'Beehiiv',
  canva: 'Canva',
  google_analytics: 'Google Analytics',
}

export const operationalLabels = {
  notion: 'Notion',
  render: 'Render',
  resend: 'Resend',
  calendly: 'Calendly',
  aws: 'AWS',
  bitwarden: 'Bitwarden',
  namecheap: 'Namecheap (domain)',
}

export const otherCostLabels = {
  legal_review: 'Legal review',
  tax_adviser: 'Tax adviser',
  bookkeeping: 'Bookkeeping',
  payment_processing: 'Payment processing',
  insurance: 'Insurance',
  recruitment_marketing: 'Recruitment / marketing',
  refund_reserve: 'Refund reserve',
  gdpr_review: 'GDPR review',
  certificates: 'Certificates',
  travel_venue: 'Travel / venue',
  bank_charges: 'Bank charges',
  accreditation: 'Accreditation',
}

export const costBasisLabels = {
  per_user_month: 'Per user / month',
  fixed_month: 'Fixed / month',
  fixed_annual: 'Fixed / year',
}
